class run_rule_engine_constant:
    INFO = "Info"
    INFO_RULE_ENGINE = "Rule Engine-Executed Successfully"

class Rule_Engine_Common_Constants:
    PROFILE_ENV_BUCKET = "profile_env_bucket"
    DB_AUDIT_TABLE = "db_audit_table"
    REGION_NAME = "region_name"
    COUNT_SOURCE_LEVEL = "count_source_level"
    COUNT_VALID = "count_valid"
    COUNT_INVALID = "count_invalid"
    STATUS = "status"
    END_TIME = "end_time"
    CLIENT_NAME = "client_name"
    BATCH_NAME  = "batch_name"
    TABLE_NAME = "table_name"
    EXECUTION_ID ="execution_id"
    BATCH_NAME="batch_name"
    DB_STATUS_TABLE = "db_status_table"
    INFO = "Info"
    COUNT_ROW_LEVEL = "count_row_level"
    ITEMS = "Items"
    BUCKET_NAME = "bucket_name"
    PROFILE_ENV = "profile_env"
    ERROR = "Error"
    ALIAS = "alias"
    CHECKFLAG = "isRuleEngine"
