class steps_constants:
    ERROR_DETAIL = "error_description"
    INFO = "Info"
    BATCH_ID = "batch_id"
    STEP_NUMBER = "step_number"
    STEP_NAME = "step_name"
    START_TIME = "start_time"
    STATUS = "status"
    STATUS_RUNNING = "Running"
    STATUS_COMPLETED = "Completed"
    STATUS_FAILED = "Failed"
    END_TIME = "end_time"


class write_constants:
    PARAMS = "params"
    PATH = "path"
    OVERWRITE = "overwrite"
    INFO = "Info"
    FORMAT = "format"
    DF = "df"


class rule_engine_constants:
    SPARK_SESSION = "spark_session"
    LOG_GROUP = "log_group"
    EXECUTION_ID = "execution_id"
    DB_STATUS_TABLE = "db_status_table"
    BATCH_NAME = "batch_name"
    CLIENT_NAME = "client_name"
    TABLE_NAME = "table_name"
    BUCKET_NAME = "bucket_name"
    DB_AUDIT_TABLE = "db_audit_table"
    REGION_NAME = "region_name"
    FILE_EXTENSION = "file_extension"
    FIELDNAME = "fieldname"
    PROFILE_ENV = "profile_env"
    PROFILE_ENV_BUCKET = "profile_env_bucket"
    DF = "df"
    PARAMS = "params"
    DB_NAME = "db_name"
    METHOD_NAME= "method_name"
    RULE_ENGINE = "RuleEngine"
    PARAMETER_ISRULENGINE = "isRuleEngine"