class Data_processor:
    TABLE_NAME ="dep_emr"
    BATCH_STATUS_TABLE = "dep_flowbuilder_batch_status"
    JOB_STATUS_TABLE = "dep_flowbuilder_job_status"
    SQS_QUEUE = "cdep.fifo"
    INSTANCE_MAP_TABLE = "dep_emr_instance_mapping"
    JOB_INPUT_TABLE = "dep_flowbuilder_job_input"
    JOB_STATUS_TABLE = "dep_flowbuilder_job_status"

    EMR_CLIENT = "emr"
    DYNAMO_CLIENT = "dynamodb"
    SQS_CLIENT = "sqs"

    EMR_STATE_RUNNING = "RUNNING"
    EMR_STATE_WAITING = "WAITING"

    READY_STATE = "Ready"
    WAIT_STATE = "Wait"

    JOB_COMPLETE = "COMPLETED"
    JOB_FAILED = "FAILED"
    JOB_CANCELLED = "CANCELLED"

    LOGS_URI = 's3://cdep/emr/logs/'
    RELEASE = "emr-6.2.0"

    MASTER_NODE = "Master"
    MARKET = "ON_DEMAND"
    MASTER_ROLE = "MASTER"
    CORE_NODE = "Core"
    CORE_ROLE = "CORE"
    INSTANCES = 1
    KEEP_ALIVE = True
    TERMINATE_PROTECT = False
    SUBNET_ID = "subnet-1ce7fc12"
    BOOTSTRAP_PATH = "s3://cdep/emr/BootStrap/BootStrap.sh"
    BOOTSTRAP_NAME = "cdep-copy-scripts"
    JOB_FLOW_ROLE = "EMR_EC2_DefaultRole"
    SERVICE_ROLE = "EMR_DefaultRole"
    TIMEOUT =300

    FIFO = "true"
    DUPLICATION = "true"
    VISIBLE_TIMEOUT = "5"

    STEP_NAME = "cdep-spark-run"
    ON_FAIL = "CANCEL_AND_WAIT"
    JAR = "command-runner.jar"
    SUBMIT = "spark-submit"
    MASTER = "yarn"
    MODE = "cluster"
    MEMORY = "6G"
    EXECUTERS = "5"
    ZIP_PATH = "s3://cdep/emr/CDEP_SCRIPTS/data_processor.zip"
    FILE_PATH = "s3://cdep/emr/CDEP_SCRIPTS/processor.py"
    LOG_GROUP = "/aws/vendedlogs/states/CDEP_STATE_MACHINE_1-Logs"
    STOPPED = "STOPPED"

class common_constants:
    INFO = "Info"
    START_TIME = "start_time"
    END_TIME = "end_time"
    JOB_NAME = "job_name"
    PROCESSING = "Processing"
    PHASE = "Phase"
    DAILY = "Daily"
    BATCH_TYPE = "batch_type"
    LOG_GROUP = "log_group"
    JOB_ID = "job_id"
    EXECUTION_ID = "execution_id"
    CLIENT_ID = "client_id"
    AVAILABLE_CLUSTERS = "Available_clusters"
    STATUS = "status"
    RUNNING = "RUNNING"
    STOPPED = "STOPPED"
    ITEMS = "Items"
    CLUSTER_ID = "cluster_id"
    ITEM = "Item"
    AVAILABLE_CORES = "Available_cores"
    BATCH_ID = "batch_id"
    CLIENT_NAME = "client_name"
    JOB_QUEUE = "Job_Queue"
    QUEUE_NAME = "Queue_name"
    JOBS = "jobs"
    BATCH_NAME = "batch_name"
    ALL = "All"
    MESSAGES = "Messages"
    MSG_EXIST = "msg_exist"
    BODY = "Body"
    CORES = "cores"
    CLUSTER_AVAILABLE = "cluster_available"
    RECEIPT_HANDLE = "ReceiptHandle"
    TOTAL_CORES = "Total_cores"
    ERROR="ERROR"
    ERROR_DETAIL = "error_detail"
    NO_OF_INSTANCE="no_of_instance"
    NO_OF_INSTANCES="no_of_instances"
    EXECUTOR_MEMORY = "executor_memory"
    REIGON_NAME = "region_name"
class check_clusters_status_constants:
    CLUSTERS = "Clusters"
    STATE = "state"
    ID = "Id"
class check_job_status_constants:
    STEPS = "Steps"
    STATUS = "Status"
    STATE = "State" 
    STEP_LIST = "Step_list"
class check_next_sqs_msg_constants: 
    BATCH_TYPE = "batch_type"
    DAILY = "Daily"
    PHASE = "phase"
    PROCESSING = "Processing"
    CLIENT_BATCH_ID = "client_batch_id"
    JOB_NAME = "job_name"
    START_TIME = "start_time"
    QUEUE_FIFO = "fifo"
    STARTING = "Starting"
    QUEUE_KEY = "data_processor_sqs"
class read_sqs_constants:
    DATA_PROCESSOR_SQS = "data_processor_sqs"
class submit_spark_job_constants:
    STEPS_PENDING = "steps_pending"
    END_TIME = "end_time" 
    BUCKET = "bucket" 
    EXTRACT = "extract" 
    STEP_LIST = "Step_list"
    JOB_NAMES = "job_names" 
    STOPPED = "STOPPED" 
    STEPS_IDS = "StepIds"
class create_emr_constants:
    MAX_CORES = "max_cores" 
    MIN_CORES = "min_cores" 
    INSTANCE_NAME = "instance_name" 
    DRIVER = "driver" 
    JOB_FLOW_ID = "JobFlowId" 
    EXTENSION_QUEUE = ".fifo"
    QUEUE_JOB = "Job_Queue" 
    LOG_GROUP = "DEP_Data_Processor"
    NUMBER_OF_INSTANCES="number_of_instances"
class logger_constant:
    PROCESSOR_NAME = "CDEP_RULE_ENGINE_PROCESSOR"
    APP_DEBUG = "Application Debug"
    STEP_SUCCESS = "Step Success"
    STEP_ERROR = "Step Error"
    JOB_SUCCESS = "Job Success"
class Resource_manage:
    DATA_PROCESSOR_LOG_GROUP ="/aws/vendedlogs/states/CDEP_STATE_MACHINE_1-Logs"
    FIFO_SUFFIX_RULE_ENGINE ="_rule_engine.fifo"
    RULE_SQS_QUEUE = "cdep_rule.fifo"
    RULE_METADATA = "dep_rule_engine_metadata"
    DEP_INSTANCE_MAPPING = "dep_instance_mapping"
    IS_ACTIVE="is_active"
    TRUE="true"
    DWH_QUEUE = "cdep.fifo"
    DWH_METADATA = "dep_flowbuilder_metadata"
    JOB_TABLE = "dep_flowbuilder_job_name"
    JOB_INPUT_TABLE = "dep_flowbuilder_job_input"
